## Assignment 1: Multiple Regression

1. Fit a model on 'speed', 'hd', 'ram', and 'screen' and plot the residuals. 
   
   Do any features have unintuitive coefficients? 
   
   Does our model predict better for certain price ranges?  
         
     <br>         
2. Fit a model including all numeric columns (add 'trend' and 'ads' to the previous model), and plot the residuals. 
   
   Do any features have unintuitive coefficients? 
   
   Does our model predict better for certain price ranges?
   
   Which residual plot looks better?

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.metrics import mean_squared_error

computers = pd.read_csv("files/Computers.csv")

computers.tail()
print(computers.shape)
print(computers.columns)
computers.head()

(6259, 10)
Index(['price', 'speed', 'hd', 'ram', 'screen', 'cd', 'multi', 'premium',
       'ads', 'trend'],
      dtype='str')

   price  speed   hd  ram  screen  cd multi premium  ads  trend
0   1499     25   80    4      14  no    no     yes   94      1
1   1795     33   85    2      14  no    no     yes   94      1
2   1595     25  170    4      15  no    no     yes   94      1
3   1849     25  170    8      14  no    no      no   94      1
4   3295     33  340   16      14  no    no     yes   94      1

### EDA

In [2]:
computers.corr(numeric_only=True)

           price     speed        hd       ram    screen       ads     trend
price   1.000000  0.300976  0.430258  0.622748  0.296041  0.054540 -0.199987
speed   0.300976  1.000000  0.372304  0.234760  0.189074 -0.215232  0.405438
hd      0.430258  0.372304  1.000000  0.777726  0.232802 -0.323222  0.577790
ram     0.622748  0.234760  0.777726  1.000000  0.208954 -0.181670  0.276844
screen  0.296041  0.189074  0.232802  0.208954  1.000000 -0.093919  0.188614
ads     0.054540 -0.215232 -0.323222 -0.181670 -0.093919  1.000000 -0.318553
trend  -0.199987  0.405438  0.577790  0.276844  0.188614 -0.318553  1.000000

### First Model

In [ ]:
cols = ["ram", "speed", "hd", "screen"]

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.459
Model:                            OLS   Adj. R-squared:                  0.458
Method:                 Least Squares   F-statistic:                     1325.
Date:                Tue, 24 Feb 2026   Prob (F-statistic):               0.00
Time:                        10:44:00   Log-Likelihood:                -46795.
No. Observations:                6259   AIC:                         9.360e+04
Df Residuals:                    6254   BIC:                         9.363e+04
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         10.3331     88.222      0.117      0.907    -162.613     183.279
ram           76.7454      1.536     49.969      0.000      73.735      79.756
speed          5.2493      0.278     18.858      0.000       4.704       5.795
hd            -0.5794      0.035    -16.520      0.000      -0.648      -0.511
screen       105.5259      6.189     17.051      0.000      93.394     117.658
==============================================================================
Omnibus:                     1640.957   Durbin-Watson:                   1.484
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5072.066
Skew:                           1.340   Prob(JB):                         0.00
Kurtosis:                       6.503   Cond. No.                     8.07e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.07e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

### Second Model

In [4]:
cols = ["ram", "speed", "hd", "screen", "ads", "trend"]

## Assignment 2: Metrics

Calculate MSE and RMSE for your regression model fitted on all numeric features.